### ISSUE TITLE
2019.4.28版本导入报错，2019没有RecalculateUVDistributionMetrics方法

### ISSUE THREAD

**Issue by yogioh123456** [LONEStudio/UnityExtensions#1]
Assets\UnityExtensions-main\UnityExtensions-main\Extensions\MeshPro\Runtime\MeshDeformer\Scripts\MeshDeformer.cs(36,18): error CS1061: 'Mesh' does not contain a definition for 'RecalculateUVDistributionMetrics' and no accessible extension method 'RecalculateUVDistributionMetrics' accepting a first argument of type 'Mesh' could be found (are you missing a using directive or an assembly reference?)

**Comment by EitanWong** [comment]
RecalculateUVDistributionMetrics方法兼容问题已经修复
建议使用Unity2020及以上版本
